version: "3.8"

services:
  api:
    build:
      dockerfile: Dockerfile
    environment:
      SECRET_KEY: "fddgdfgdfgdfgdsdewfwefwefewfewf343434434" # Add this
      ACCESS_TOKEN_EXPIRE_MINUTES: "30"
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin # Corrected the spelling
      POSTGRES_PASSWORD: adminpass # Corrected the spelling
      POSTGRES_DB: fastapi_db # Corrected the spelling
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Use ':' instead of '='
      PGADMIN_DEFAULT_PASSWORD: adminpass # Use ':' instead of '='
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  postgres_data:
